# Generated by Django 3.1.3 on 2021-08-26 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=40, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='mo')),
                ('keyword', models.TextField(null=True)),
            ],
        ),
    ]
