# Generated by Django 3.1.3 on 2021-08-26 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210826_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='media',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='upload',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
