# Generated by Django 3.1.3 on 2021-08-26 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210826_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
